### ISSUE TITLE
Cookie prompts / pop-up windows

### ISSUE THREAD

**Issue by krystof-k** [workeffortwaste/layout-shift-gif#12]
It'd be great if you try to close the cookie prompts / pop-up windows (or being able to specify which element to click). E.g.:

![image](https://github.com/workeffortwaste/layout-shift-gif/assets/11633481/513a878a-2796-41bd-b6c3-55bf2a977e60)

**Comment by workeffortwaste** [comment]
It's possible to skip these by supplying your own compatible cookie file in JSON format.

I recommend this extension for Chrome: https://chromewebstore.google.com/detail/export-cookie-json-file-f/nmckokihipjgplolmcmjakknndddifde?hl=en

Visit the website in your usual browser, accept the cookies, and use the extension to export the cookies as JSON.

You can then usse the following command and it will import the cookies and bypass the CMP.

`layout-shift-gif --url <url> --cookies ./cookies.json`
