### ISSUE TITLE
Output the whole page

### ISSUE THREAD

**Issue by catalinux** [workeffortwaste/layout-shift-gif#2]
Is there a way I could output the whole page to the gif. I have pages that are very tall: multiple screens

**Comment by workeffortwaste** [comment]
I'll add that as an option to the CLI version when I next get a chance.

**Comment by workeffortwaste** [comment]
You can now specify the width and the height of the viewport in the CLI version, which will let you generate a gif for an entire page if you want.

https://github.com/workeffortwaste/layout-shift-gif/releases/tag/1.1.0
