### ISSUE TITLE
Options width and height generat a repeated  container

### ISSUE THREAD

**Issue by catalinux** [workeffortwaste/layout-shift-gif#3]
I tried to run

` layout-shift-gif --url https://blacklivesmatter.com/ --device mobile --output layout-shift.gif --width=650 --height=
5000`

This is the file that was generated, no picture with the t-shirt

![layout-shift](https://user-images.githubusercontent.com/2072712/96915923-864da580-14af-11eb-8c29-3010f2c86ad1.gif)

**Comment by workeffortwaste** [comment]
This should be fixed now, thanks for catching this.

https://github.com/workeffortwaste/layout-shift-gif/releases/tag/1.1.1
