### ISSUE TITLE
An option to bypass Error: net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by cesrafa** [workeffortwaste/layout-shift-gif#4]
Hi =) 
Is there a change you could add a way to use a localhost with https? Of course, the main problem about this is that I always have to add an exception when I navigate through a visual browser, pero using this project as a npm program through the terminal throws an error about my website's certificate. 

Btw, excellent project!

**Comment by workeffortwaste** [comment]
Thanks for the suggestion, I'll take a look at getting that sorted for you.

**Comment by workeffortwaste** [comment]
This is now possible with version 1.1.3.
