### ISSUE TITLE
Installs fine but cannot run (Macbook M1)

### ISSUE THREAD

**Issue by wormeyman** [workeffortwaste/layout-shift-gif#7]
I figure this is related to having an M1, any ideas?

╭─ericjohnson@ej-mba-m1 ~
╰─$ npm install -g layout-shift-gif

added 126 packages, and audited 127 packages in 15s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
╭─ericjohnson@ej-mba-m1 ~
╰─$ layout-shift-gif --url https://blacklivesmatter.com/ --device mobile --output layout-shift.gif
TimeoutError: Timed out after 10000 ms while trying to connect to the browser! Only Chrome at revision r869685 is guaranteed to work.
    at Timeout.onTimeout (/opt/homebrew/lib/node_modules/layout-shift-gif/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:205:20)

**Comment by workeffortwaste** [comment]
This should be resolved in https://github.com/workeffortwaste/layout-shift-gif/releases/tag/1.3.0
