### ISSUE TITLE
Include Readme and explanation of colors/border styles

### ISSUE THREAD

**Issue by pm0u** [workeffortwaste/layout-shift-gif#8]
While using the tool, I am presented with information about the CLS on the page via colored rectangles (I have seen green and orange) that animate by either popping into the gif or having their border-style change (from solid to dashed or vice versa).

What do the different colors and border styles indicate?

**Comment by pm0u** [comment]
an example:

![blog](https://user-images.githubusercontent.com/410558/124795974-de2d1f00-df0d-11eb-843a-7486076d9be8.gif)

**Comment by Donderda** [comment]
any updates on this? It's a really good tool to see *that* something is happening, but I'm not sure *what* happens :).

**Comment by workeffortwaste** [comment]
I haven't forgotten about this, just haven't found the time to return to this project and add better documentation yet.

**Comment by workeffortwaste** [comment]
This is now added in https://github.com/workeffortwaste/layout-shift-gif/releases/tag/1.3.0

**Comment by Donderda** [comment]
Thank you very much!
